---
name: Static Executable

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

jobs:
  build-executable:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    name: Static build on ${{ matrix.os }}
    runs-on: ${{ matrix.os}}
    steps:
      - name: Checkout repository
        uses: >- # v4.1.1
          actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Install Nix
        uses: >- # Custom commit, last pinned 2023-10-30
          DeterminateSystems/nix-installer-action@721f94f7df2665d750964b01ac153ce9c1151e57
      - name: Cache custom Nix derivations
        uses: >- # Custom commit, last pinned 2023-10-28
          DeterminateSystems/magic-nix-cache-action@a04e6275a6bea232cd04fc6f3cbf20d4cb02a3e1

      - name: Build executable
        run: nix build

      - name: Upload artifact
        uses: >- # v3.1.3
          actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: turbo-cache
          path: result
